### ISSUE TITLE
How to access relationship URLs

### ISSUE THREAD

**Issue by switz** [exogen/graphbrainz#90]
https://musicbrainz.org/artist/e01646f2-2a04-450d-8bf2-0d993082e058/relationships

I want to pull the instagram URL of this band, so I wrote a query like:

```
  lookup {
    artist(mbid: "e01646f2-2a04-450d-8bf2-0d993082e058") {
      id
      mbid
      name
      sortName
      relationships {
        urls {
          edges {
            node {
              sourceCredit
              targetCredit
              begin
              end
              ended
              type
              typeID
              attributes
              direction
            }
          }
        }
      }
    }
  }
```

But I don't see any way of getting the title and URL of the relationship. Any insight?

Thanks for an amazing library, it really is super helpful.

**Comment by exogen** [comment]
Hi @switz! I'm happy to see it's being used and coming in handy! 😄 

For this you'll need the `target` property of `node`. Since relationships can target most other types, its type is `Entity` which means you need to get more specific and tell it you want the `resource` property from the `URL` type in particular:

```gql
{
  lookup {
    artist(mbid: "e01646f2-2a04-450d-8bf2-0d993082e058") {
      id
      mbid
      name
      sortName
      relationships {
        urls {
          edges {
            node {
              sourceCredit
              targetCredit
              begin
              end
              ended
              type
              typeID
              attributes
              direction
              target {
                ...on URL {
                  resource
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Let me know if that works?

**Comment by switz** [comment]
WOW! that's amazing, and with the instant reply no less. I really appreciate it. I've never seen that spread/`on` syntax, I'll have to read up on what graphql is doing behind the scenes.

Thanks so so so much!

**Comment by exogen** [comment]
You're welcome! 🙌

Here's the relevant section of GraphQL docs: https://graphql.org/learn/queries/#inline-fragments

In this case it's applicable because the schema is designed so that anything with an MBID (like the MusicBrainz URL type) extends the `Entity` interface.
